### ISSUE TITLE
xiaoqu_to_db.py在无法通过命令行模式自动运行

### ISSUE THREAD

**Issue by NikomimiSaya** [jumper2014/lianjia-beike-spider#13]
C:\Users\\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pymysql\cursors.py:170:`

 Warning: (1366, "Incorrect string value: '\\xD6\\xD0\\xB9\\xFA\\xB1\\xEA...' for column 'VARIABLE_VALUE' at row 519")
  result = self._query(query)
Which city data do you want to save ?
bj: 北京, cd: 成都, cq: 重庆, cs: 长沙
dg: 东莞, dl: 大连, fs: 佛山, gz: 广州
hz: 杭州, hf: 合肥, jn: 济南, nj: 南京
qd: 青岛, sh: 上海, sz: 深圳, su: 苏州
sy: 沈阳, tj: 天津, wh: 武汉, xm: 厦门
yt: 烟台,

xiaoqu.py等python脚本可以通过命令行加参数直接执行这个导入数据库的却不能通过命令行执行不便于自动收集

**Comment by jumper2014** [comment]
好建议，支持！
d5181f74a3e8b58d5e57b1efa6c616bbc3dd5eae
