### ISSUE TITLE
希望能够修改一下生成xiaoqu的命名逻辑

### ISSUE THREAD

**Issue by peng-cai** [jumper2014/lianjia-beike-spider#14]
我认为用抓取到的小区信息生成csv或者写入数据库的时候应该带有时间而不是直接覆盖
例如默认情况下xiaoqu_to_db.py生成的csv文件为xiaoqu.csv在自动化部署时会覆盖前一天的csv
写入数据库的时候建议把表名由xiaoqu改为城市名有利于减少数据分类的工作量

**Comment by jumper2014** [comment]
这个涉及到所有持久化的命名，还没想好如何统一，暂时先不处理。

**Comment by harryge00** [comment]
有前端页面或者小程序能查已经爬的数据吗

**Comment by jumper2014** [comment]
不好意思，没有

发自我的 iPhone
