### ISSUE TITLE
webbrowser 这个包为啥安装不了？

### ISSUE THREAD

**Issue by abner7777** [jumper2014/lianjia-beike-spider#16]

**Comment by jumper2014** [comment]
xiaoqu_to_chart.py仅仅支持mac系统

**Comment by laijs** [comment]
@jumper2014 如果不使用 xiaoqu_to_chart.py 也就不需要webbrowser 这个包吗？

**Comment by zchrissirhcz** [comment]
Hi, 我是mac系统，但是pip install -r requirements.txt的时候也提示webbrwoser包装不了，没有合适版本。求解？
