### ISSUE TITLE
关于支持python2

### ISSUE THREAD

**Issue by wkd-lidashuang** [jumper2014/lianjia-beike-spider#17]
代码中所有print都是采用python3结构。根本没办法支持python2。在get_city()中添加版本判断个人感觉是可以删掉的。

**Comment by jumper2014** [comment]
你是说你在python2下不能使用么？我在Python2下面是好的啊。你Python2下面报什么错贴出来。

**Comment by wkd-lidashuang** [comment]
我弄错了。是可以的。
