### ISSUE TITLE
建议添加抓取延时

### ISSUE THREAD

**Issue by jiangwei1995910** [jumper2014/lianjia-beike-spider#21]
做为一名高素质爬虫coder，建议配置文件加一个随机延时选项，要是别人服务器顶不住了，一封爬虫，大家都GG，另外建议爬取数据可以直接存数据，不经过csv

**Comment by jumper2014** [comment]
base spider中增加RANDOM_DELAY开关，用于控制随机延时。

**Comment by jiangwei1995910** [comment]
thanks
