### ISSUE TITLE
遇到的一个关于浏览器的问题

### ISSUE THREAD

**Issue by AZul-DTZ** [jumper2014/lianjia-beike-spider#26]
作者你好，感谢你的开发和分享
我在运行pip install -r requirements.txt时出现以下报错信息
 Could not find a version that satisfies the requirement webbrowser (from -r requirements.txt (line 13)) (from versions: none)
ERROR: No matching distribution found for webbrowser (from -r requirements.txt (line 13))
请问这个是跟我的浏览器版本有关吗？按网上指示将python的pip升级到了最新仍无效。
请教一下应该如何解决？

**Comment by jumper2014** [comment]
这个包不是必须的，windows上装不了。
我把requirements.txt这行删掉了，你本地更新下再装。

**Comment by AZul-DTZ** [comment]
好的 十分谢谢！
已经解决。


在2019年6月21日 07:59，旺福<notifications@github.com> 写道：

Closed #26.
