### ISSUE TITLE
现在还能用吗？链家加了反爬虫

### ISSUE THREAD

**Issue by rclijia** [jumper2014/lianjia-beike-spider#27]
现在得不到任何数据，
https://bj.lianjia.com/ 返回的页面信息第45行里有反爬虫的代码，
是被封了吗？？

**Comment by jumper2014** [comment]
什么报错信息？

**Comment by rclijia** [comment]
运行不报错，但抓不到任何数据

**Comment by greatgaoyou** [comment]
运行会出这么个提示，主机关闭一个访问进程之类的。
运行完了有excel文件，但是没有内容，0k






------------------ 原始邮件 ------------------
发件人: rclijia <notifications@github.com>
发送时间: 2019年7月10日 17:52
收件人: jumper2014/lianjia-beike-spider <lianjia-beike-spider@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[jumper2014/lianjia-beike-spider] 现在还能用吗？链家加了反爬虫 (#27)




运行不报错，但抓不到任何数据

**Comment by jumper2014** [comment]
把运行的命令和输出都贴一下吧，否则没法分析

**Comment by greatgaoyou** [comment]
租房的爬出来的数据都是0k的，二手房还是有一些数据的


------------------ 原始邮件 ------------------
发件人: "旺福"<notifications@github.com>;
发送时间: 2019年7月11日(星期四) 晚上10:17
收件人: "jumper2014/lianjia-beike-spider"<lianjia-beike-spider@noreply.github.com>;
抄送: "金玉松"<jysgaoyou@foxmail.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [jumper2014/lianjia-beike-spider] 现在还能用吗？链家加了反爬虫 (#27)




把运行的命令和输出都贴一下吧，否则没法分析

**Comment by rclijia** [comment]
![lianjia](https://user-images.githubusercontent.com/5274430/61178358-10a52980-a61e-11e9-87bb-9fca4e2ea629.png)
这是链家首页的源码，反爬虫那块有效果吗？

**Comment by futurexiong** [comment]
贝壳也爬不到数据了，返回200ok但是没有数据

**Comment by jinjim** [comment]
![image](https://user-images.githubusercontent.com/8455083/65041189-b9f2fd80-d988-11e9-8990-be5dc8cdcb9e.png)

**Comment by xm13592** [comment]
现在还可以用，可以爬到数据，返回没有数据应该是自己在改代码的时候哪里改错了

**Comment by jumper2014** [comment]
好的，既然好用，就先关闭该问题了。
