### ISSUE TITLE
可否增加爬取坐标字段

### ISSUE THREAD

**Issue by foldation** [jumper2014/lianjia-beike-spider#28]
如题,感谢.
这个帖子里面说了字段位置,http://www.dongchangbin.net.cn/?p=701

**Comment by jumper2014** [comment]
之前考虑过，但是最近没有时间弄，要不你尝试下，提个merge request？

**Comment by elegantcoin** [comment]
> 如题,感谢.
> 这个帖子里面说了字段位置,http://www.dongchangbin.net.cn/?p=701

爬取坐标后可以计算距离矩阵，也可以调用百度地图API （http://lbsyun.baidu.com/index.php?title=jspopular/guide/geocoding）解析坐标对应的地址，查看所要入住的地图信息。

**Comment by jumper2014** [comment]
你可以自己尝试下，弄好了提交pr
